---
title: "Enonkishu Machine Learning Test"
output: html_notebook
author: "Guy Lomax"
date: 2023-05-16
---

```{r setup}

library(tidyverse)
library(caret)
library(ranger)
library(sf)
library(terra)
library(lubridate)
library(tmap)
library(here)

tmap_mode("view")

```


```{r load_data, warning = F}

# Grazing blocks
grazing_blocks <- st_read(here("data", "raw", "vector", "enonkishu", "grazing_block.shp"),
                          quiet = T)

# Vegetation transect locations
transect_paths <- Sys.glob(here("data", "raw", "vector", "enonkishu",
                                "biomonitoring_transects_kml", "*.kml"))

transects <- lapply(transect_paths, st_read, quiet = T) %>%
  bind_rows()

# Vegetation transect data
transect_data <- readxl::read_xlsx(here("data", "raw", "csv", "enonkishu",
                                "Enonkishu_Biomonitoring_March 2023.xlsx"),
                                sheet = "Cumulative",
                                skip = 1,
                                guess_max = 2000) %>%
  filter(!is.na(Location))

transect_names <- read_csv(here("data", "raw", "csv", "enonkishu",
                                "parameter_names.csv"),
                           col_types = "cc")

transect_join_table <- read_csv(here("data", "raw", "csv", "enonkishu",
                                     "transect_join_table.csv"))
                                

```


Cleaning data and joining transect data to location

```{r clean_data}

transect_data_clean <- transect_data %>%
  select(3, 4, 6, 12:30, 38) %>%
  rename_with(.cols = matches("\\d"),
              .fn = function(x) {transect_names$Name[transect_names$Parameter == x]}) %>%
  rename(plant_density_pc = "Plant Density %") %>%
  left_join(transect_join_table, by = c("Location" = "dataset_name")) %>%
  filter(!is.na(transect_code_kml))
  
head(transect_data_clean)

transect_data_clean %>%
  count(transect_name) %>%
  view()

transect_data_filtered <- transect_data_clean %>%
  group_by(transect_name, Date) %>%
  filter(n() == 5) %>%
  summarise(season = first(Season),
            transect_code_kml = first(transect_code_kml),
            block = first(block),
            land_cover = first(land_cover),
            across(.cols = all_of(transect_names$Name),
                   .fns = mean),
            plant_density_pc = mean(plant_density)) %>%
  ungroup()

transects_data <- left_join(transect_data_filtered, transects,
                            by = c("transect_code_kml" = "Name"))

# Export locations and data for Google Earth Engine test
transects_data %>%
  mutate(x = st_coordinates(geometry)[,1],
         y = st_coordinates(geometry)[,2],
         Date = as_date(Date)) %>%
  st_write(here("data", "processed", "csv", "enonkishu",
                "enonkishu_transects_data.csv"),
           delete_dsn = TRUE)

```

```{r eda}

variables <- transect_names$Name
vars_to_show <- c("plant_density", "plant_height", "leaf_area",
                  "overgrazed", "total_cover")

transects_data %>%
  pivot_longer(cols = all_of(variables),
               names_to = "var",
               values_to = "value") %>%
  filter(var %in% vars_to_show) %>%
  mutate(name_lc = paste0(transect_name, "_", land_cover)) %>%
  ggplot(aes(x = Date, y = value, colour = var)) +
  geom_line(lwd = 1) +
  facet_wrap(~name_lc, nrow = 4, ncol = 3) +
  theme_bw()
```

