---
title: "Mapping relative productivity index (RPI)"
output: html_notebook
author: Guy Lomax
date: 2023-08-18
---

This Notebook uses quantile regression models fitted on sample data to map
the annual relative productivity index across Kenyan and Tanzanian rangelands
from 2000 to 2018.

TO DO:
1. Fix input layers to filter only to rangeland pixels
2. Include % woody layer to allow fitting of correct model


```{r setup, include = FALSE}

# Data handling
library(tidyverse)
library(sf)
library(terra)
library(here)

# Analysis
library(qgam)
library(gratia)
library(parallel)
library(furrr)
library(tictoc)
library(beepr)

# Visualisation
library(tmap)

tmap_options(check.and.fix = TRUE)

# Set up parallel computing
nc <- detectCores() - 1
plan(multisession, workers = nc)


```


```{r load, include = FALSE}

# Country boundaries
countries <- st_read(here("data", "raw", "vector", "natural_earth",
                          "ne_110m_admin_0_countries_fixed.shp"))

ke_tz <- countries %>% filter(NAME %in% c("Kenya", "Tanzania"))

# Covariate layers
# Static
static_covariates <- rast(here("data", "raw", "raster", "covariateMaps",
                                 "staticVars.tif"))

twi <- rast(here("data", "processed", "raster", "hydroSHEDS",
                 "hydrosheds_twi_fd8.tif"))

# Load dynamic covariates as a named list of rasters (one per year)
dynamic_covariates_paths <- Sys.glob(here("data", "raw", "raster", "covariateMaps",
                                          "dynamicVars*.tif"))

years <- str_extract(dynamic_covariates_paths, "\\d\\d\\d\\d")
dynamic_covariates <- map(dynamic_covariates_paths, rast)
names(dynamic_covariates) <- years

# Fitted models

models <- read_rds(here("data", "processed", "rds", "binned_gam.rds"))

```

Prepare data for prediction

```{r data_prep}

# Reproject TWI to same resolution and CRS as other layers

twi_reproj <- project(twi, static_covariates)

# Crop twi and static covariates to dynamic covariates layers
# (GEE doesn't match extents properly due to resampling)

twi_crop <- crop(twi_reproj, dynamic_covariates[[1]])
static_crop <- crop(static_covariates, dynamic_covariates[[1]])

# For each year, create a data frame for prediction

extract_covariates <- function(dynamic_rast, year) {
  
  # Progress message
  message(paste0("Processing year ", year))
  
  # Extract and join rasters
  all_covariates <- c(dynamic_rast, static_crop, twi_crop)
  
  # Mask to Kenya/Tanzania
  all_covariates_masked <- mask(all_covariates, ke_tz)
  
  # Convert raster to data frame
  covariate_df <- as.data.frame(all_covariates_masked, xy = TRUE, cells = TRUE)
  
  # Add year information
  covariate_df$year <- as.numeric(year)
  
  covariate_df
}

covariate_dfs <- map2(dynamic_covariates, names(dynamic_covariates), extract_covariates)

write_rds(covariate_dfs,
          here("data", "processed", "rds", "covariate_dfs.rds"))

```


```{r fitted_values}

covariate_dfs <- read_rds(here("data", "processed", "rds", "covariate_dfs.rds"))

# Prepare variables for fitting
clean_df <- function(df) {
  df_clean <- df %>%
    filter(!is.na(GPP)) %>%
    rename(twi = hydrosheds_twi_fd8,
           parMean = GMT_0900_PAR) %>%
    mutate(woody = shrubland + trees,
           woody_bin = cut_interval(woody, 5))
  
  df_clean
}

# Add fitted values to sample table

add_fitted <- function(data, model_df) {
  
  joined_df <- data %>%
    group_by(woody_bin) %>%
    nest() %>%
    arrange(woody_bin) %>%
    cbind(models$model)
  
  # df_fitted <- joined_df %>%
  #   mutate(fitted = map2(model, data, predict.gam)) %>%
  #   mutate(data = map2(data, fitted, cbind)) %>%
  #   select(-fitted, -model) %>%
  #   unnest(data) %>%
  #   ungroup() %>%
  #   rename("fitted" = ".y[[i]]")
  
  # df_fitted
  joined_df
}

tic()
fitted_dfs <- covariate_dfs %>%
  map(clean_df) %>%
  map(covariate_dfs, add_fitted, model_df = models)
toc()
beep(3)

# Calculate RPI

sample_points_fitted <- sample_points_binned %>%
  group_by(woody_bin) %>%
  nest() %>%
  left_join(models_fitted, by = c("woody_bin" = "bins")) %>%
  mutate(fitted = map2(model, data, predict.gam)) %>%
  mutate(data = map2(data, fitted, cbind)) %>%
  select(-fitted, -model) %>%
  unnest(data) %>%
  ungroup() %>%
  rename("fitted" = ".y[[i]]")

# Calculate RPI
sample_points_rpi <- sample_points_fitted %>%
  select(id, year, x, y, precipitation, GPP, fitted, woody_bin) %>%
  mutate(rpi = GPP / fitted)

# Visualise RPI patterns

sample_points_rpi %>%
  ggplot(aes(x = as.factor(year), y = rpi, fill = woody_bin)) +
  geom_boxplot(outlier.size = 0.2) +
  geom_hline(yintercept = c(0,1)) +
  ylim(0, 3) +
  theme_bw()

sample_points_rpi %>%
  ggplot(aes(x = as.factor(year), y = rpi)) +
  geom_jitter(size = 0.1, alpha = 0.25) +
  geom_hline(yintercept = c(0,1)) +
  ylim(0, 3) +
  theme_bw()

sample_points_rpi %>%
  group_by(year) %>%
  mutate(map = mean(precipitation)) %>%
  ungroup() %>%
  mutate(max_map = max(map),
         map_norm = map / max_map) %>%
  ggplot() +
  geom_jitter(aes(x = as.factor(year), y = rpi), size = 0.1, alpha = 0.2) +
  geom_point(aes(x = as.factor(year), y = map_norm), size = 2, colour = "lightblue") +
  ylim(0, 3) +
  theme_bw()

# Test correlations between rpi and precipitation (should be minimal correlation)

cor_test <- sample_points_rpi %>%
  group_by(year) %>%
  summarise(med_rpi = median(rpi),
            mean_rpi = mean(rpi),
            map = mean(precipitation))

cor(cor_test)

cor(sample_points_rpi$precipitation, sample_points_rpi$rpi)
plot(sample_points_rpi$precipitation, sample_points_rpi$rpi, cex = 0.05)


```
Apply to full study area to map annual RPI

```{r rpi_map}

```

